# Generated by Django 4.1.5 on 2023-01-13 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_create_at_cart_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
